
= MicroProfile OpenTelemetry

This specification is to adopt https://opentelemetry.io/ [OpenTelemetry] from CNCF to allow MicroProfile Applications benefit from 
OpenTelemetry and enable Jakarta RESTful Web Services automatically being traced.

== OpenTracing move to OpenTelemetry
With the merge of OpenTracing and Open Census, OpenTelemetry is the new future. 
OpenTelemetry consists of Tracing, Logging and Metrics support. This reposition is to start with Tracing part first with the potential to add logging support.

== Multiple modules
Since this specification potentially expands to support logging from OpenTelemetry, it will use multi module structure. 
For the time being, the main focus is OpenTelemetry Tracing. When OpenTelemtry Logging is ready for production, we will then evaluate the need to pull in the OpenTelemetry Logging.

== Directly adopt the APIs from OpenTelemetry Tracing

This specification directly expose the Tracing APIs from OpenTelemetry and then provide CDI and Jakarta RESTful Web Services integration.
The https://github.com/open-telemetry/opentelemetry-java/tree/main/api/all/src/main/java/io/opentelemetry/api/trace Tracer APIs from OpenTelemetry will be exposed.
This specification does not plan to reinvent the wheels but rather exposes OpenTelemetry APIs due to the following reasons:
* OpenTelemetry is a specification under CNCF 
* OpenTelemetry is widely adopted by different vendors and languages
* OpenTelemetry has Java API and annotations that are readily to be used
* OpenTelemetry is active and open for the collaboration with us
* OpenTelemetry is platform technology and we use the effort to make Java libraries to be used directly instead of reinventing our own APIs
* OpenTelemetry is serious with backward incompatible changes and communicates openly
MicroProfile pulls in a particular version of OpenTelemetry. Whenever we upgrade, we evaluate the backward compatibility status ourselves as well.

== MicroProfile OpenTelemetry Tracing
MicroProfile OpenTelemetry pulls in OpenTelemetry tracing and integrate with CDI and Jakarta Restful Services. It provides three types of instrumentations:

* Automatic Instrumentation

Jakarta RESTful Web Services (server and client), and MicroProfile REST Clients are automatically enlisted to participate in distributed tracing without code modification as specified in the Tracing API.

* Manual Instrumentation

Explicit manual instrumentation can be added into a MicroProfile application using annotation or programmatic lookup.

* Agent Instrumentation

Implementations are free to support the OpenTelemetry Agent Instrumentation.

=== References

The following repo was used to try out some of the possible integrations between MP OpenTracing and OpenTelemetry:

* https://github.com/quarkiverse/quarkus-microprofile/tree/opentelemetry

Note that Quarkus already provides an integration extension with OpenTelemetry. 

==== CDI Extension Prototype
https://github.com/smallrye/smallrye-opentelemetry/tree/main/implementation/src/main/java/io/smallrye/opentelemetry/implementation
