//
// Copyright (c) 2019 Contributors to the Eclipse Foundation
//
// See the NOTICE file(s) distributed with this work for additional
// information regarding copyright ownership.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
image:https://badges.gitter.im/eclipse/microprofile-sandbox.svg[link="https://gitter.im/eclipse/microprofile-sandbox"]

= Working Area For a MicroProfile Event Sourcing Specification Proposal

== Event Sourcing

For a general definition of 'Event Sourcing' see: https://martinfowler.com/eaaDev/EventSourcing.html

This project is a working area for a proposal for MicroProfile Event Sourcing built on top of MicroProfile Reactive Messaging: https://github.com/eclipse/microprofile-reactive-messaging

It also makes a great deal of reference to the ideas and code built up as part of
the Debezium and Apache Kafka projects.

There is prototyping and dicusssion work going on in this repository: 
https://github.com/smallrye/smallrye-event-sourcing

The main thoughts are currently recorded in this file:
https://github.com/eclipse/microprofile-sandbox/blob/master/proposals/event-sourcing/proposal/src/main/asciidoc/proposal.asciidoc

=== Contributing

If you are interested in contributing to this proposal feel free to fork and raise issues or PRs at
https://github.com/eclipse/microprofile-sandbox

This file is in the proposals/event-sourcing folder.

If you are interested in contributing to a prototype implementation then please
head over to the https://github.com/smallrye/smallrye-event-sourcing project. 

=== Building the project

The build environment for this requires a working (together) version of maven and Java.
Go to the _event-sourcing_ folder and enter `mvn clean package` at the command line. 

