//
// Copyright (c) 2019 Contributors to the Eclipse Foundation
//
// See the NOTICE file(s) distributed with this work for additional
// information regarding copyright ownership.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
[[at_ignore]]
=== @Ignore

Allows to exclude an otherwise mapped element. Mostly useful to e.g. mark a field as excluded in input only.

The behavior is different depending on where `@Ignore` annotation is placed.

* *On field:* Field is ignored in both graphql type and input type.
* *On getter:* Field is ignored in the graphql type.
* *On setter:* Field is ignored in the graphql input type.

.Example
[source,java,numbered]
----
@Type(value = "Starship", description = "A starship from Starwars")
@InputType(value = "StarshipInput", description = "Input object for a starship")
public class Starship {
    @InputField(value = "uuid", description = "uuid of a new Starship")
    private String id;
    private String name;
    private float length;
    private float mass;
    @Ignore
    private String color;

    //  Getters, setters…
   
    public float getLength() {
        return length;
    }
   
    @Ignore
    public void setLength(float length) {
        this.length = length;
    }

    @Ignore
    public float getMass() {
        return mass;
    }

    public void setMass(float mass) {
        this.mass = mass;
    }
}
----

Resulting schema SDL:

[source,json,numbered]
----
# A starship from Starwars
type Starship {
    id: String
    name: String
    length: Float
}

# Input object for a starship
input Starship {
    # uuid of a new Starship
    uuid: String
    name: String
    mass: Float
}
----