//
// Copyright (c) 2019 Contributors to the Eclipse Foundation
//
// See the NOTICE file(s) distributed with this work for additional
// information regarding copyright ownership.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
[[at_input_type]]
=== @InputType

Controls the mapping of the annotated Java type to a GraphQL input object type.

.Parameters
[cols="1,1"]
|===
|*value*|The name the corresponding input object type should have in the GraphQL schema
|*description*|The description of the corresponding input object type
|===

.Example
[source,java,numbered]
----
@Type(value = "Starship", description = "A starship from Starwars")
@InputType(value = "StarshipInput", description = "Input object for a starship")
public class Starship {
   private String id;
   private String name;
   private float length;

   //  Getters, setters...
}
----
[source,java,numbered]
----
public class StarshipService {
  @Mutation(value = "saveStarship", description = "Save a new starship")
  public Starship save(Starship starship) {
     // ...
  }
}
----

Resulting schema SDL:

[source,json,numbered]
----
# Input object for a starship
input Starship {
   id: String
   name: String
   length: Float
}
----

[source,json,numbered]
----
type Mutation {
  # Creates and saves a new starship
  saveStarship(starship: StarshipInput): Starship
}
----